/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class db_DBManager */

#ifndef _Included_db_DBManager
#define _Included_db_DBManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     db_DBManager
 * Method:    loadDb
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_db_DBManager_loadDb
  (JNIEnv *, jobject, jstring);

/*
 * Class:     db_DBManager
 * Method:    doQuery
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_db_DBManager_doQuery
  (JNIEnv *, jobject, jstring);

/*
 * Class:     db_DBManager
 * Method:    outputTableNames
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_db_DBManager_outputTableNames
  (JNIEnv *, jobject);

/*
 * Class:     db_DBManager
 * Method:    exportDatabaseCustom
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_db_DBManager_exportDatabaseCustom
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
